"""add link_previews table

Revision ID: c418ac25785e
Revises: cd4c6b034421
Create Date: 2026-07-17 10:52:59.115686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c418ac25785e'
down_revision: Union[str, Sequence[str], None] = 'cd4c6b034421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_previews',
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('fetch_failed', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('url_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link_previews')
    # ### end Alembic commands ###
